# Generated by Django 4.2.5 on 2023-09-09 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex_app', '0003_alter_caughtpokemon_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caughtpokemon',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
    ]
